### ISSUE TITLE
concurrency issue / race condition

### ISSUE THREAD

**Issue by Darkvater** [json-path/JsonPath#975]
Hi,

I've been investigating strange behaviour in wiremock (see https://github.com/wiremock/wiremock/issues/706#issuecomment-1862732727) and over the course of several days narrowed the issue down to a race condition in json-path. While I am still trying to pin down the exact culprit please find my findings below. Maybe someone with intimate knowledge of the library can see immediately what is wrong which would save me a lot of time.

- version used: json-path 2.8.0 (but json-path 2.7.0 exhibits the same behaviour)
- issue: `JsonPath.read(<<json>>, "concat($.keys())")` returns the keys from a json called in a different thread

### log and explanation
- I have annotated certain classes with logging.
- the log format is `[<thread-id> - <class-instance-hash>] <class-name>::<method> ... parameters of interest]`
- I have simplified the log here a bit to give the same simple name to all objects that are the same. So everywhere you see `<<BODY>>` it means the same JSON payload; everywhere you see `<<CONFIG>>` it is the same object instance.
- you can see from the log there is a recursive call here to evaluate `$.keys` and then `concat()`
- somewhere after correctly evaluating `$.keys` to "transactionId-ZFOr/PRIIPS" the result of EvaluationContext::addResult on `concat()` is suddenly "transactionId-ZFOr/MIFID" which is another call. You can see this between the section highlighted in -----

### notes
- I'm adding some more logging to check evaluation context's valueResult and indexes there, but each run takes a while as it really only happens occasionally, and even less so with the extra logging added

```bash
[qtp1615908941-218 - <<JSON_PATH_1>>]          JSONPATH::read jsonObject: <<BODY>>, configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>

[qtp1615908941-218 - <<COMPILED_PATH_1>>]      COMPILEDPATH::evaluate-1.0 document: <<BODY>>, rootDocument: <<BODY>>, configuration: <<CONFIG>>
[qtp1615908941-218 - <<COMPILED_PATH_1>>]      COMPILEDPATH::evaluate-2.0 path: $.concat(...), document: <<BODY>>, rootDocument: <<BODY>>, configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<COMPILED_PATH_1>>]      COMPILEDPATH::evaluate-2.1 ctx: <<EVALUATIONCTX>>, path: $.concat(...), configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<COMPILED_PATH_2>>]      COMPILEDPATH::evaluate-1.0 document: <<BODY>>, rootDocument: <<BODY>>, configuration: <<CONFIG>>
[qtp1615908941-218 - <<COMPILED_PATH_2>>]      COMPILEDPATH::evaluate-2.0 path: $.keys(), document: <<BODY>>, rootDocument: <<BODY>>, configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<COMPILED_PATH_2>>]      COMPILEDPATH::evaluate-2.1 ctx: <<EVALUATIONCTX_2>>, path: $.keys(), configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<EVALUATION_CONTEXT_1>>] EVALUATIONCONTEXTIMPL::addResult-1 path: $.keys, model: [transactionId-ZFOr/PRIIPS], configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<EVALUATION_CONTEXT_1>>] EVALUATIONCONTEXTIMPL::addResult-2 valueResult: [[transactionId-ZFOr/PRIIPS]], resultIndex: 0, configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<EVALUATION_CONTEXT_1>>] EVALUATIONCONTEXTIMPL::addResult-3 valueResult: [[transactionId-ZFOr/PRIIPS]], resultIndex: 0, configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<COMPILED_PATH_2>>]      COMPILEDPATH::evaluate-2.2 ctx: <<EVALUATIONCTX_2>>, path: $.keys(), configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<COMPILED_PATH_2>>]      COMPILEDPATH::evaluate-2.4 ctx: <<EVALUATIONCTX_2>>, path: $.keys(), configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<COMPILED_PATH_2>>]      COMPILEDPATH::evaluate-1.1 result: <<EVALUATIONCTX_2>>, document: <<BODY>>, rootDocument: <<BODY>>, configuration: <<CONFIG>>
[qtp1615908941-218 - <<EVALUATION_CONTEXT_1>>] EVALUATIONCONTEXTIMPL::getValue-1.1 value: [transactionId-ZFOr/PRIIPS], unwrap: true
[qtp1615908941-218 - <<EVALUATION_CONTEXT_1>>] EVALUATIONCONTEXTIMPL::getValue-1.2 result: [transactionId-ZFOr/PRIIPS], unwrap: true
--------------------------------------------------------------------------------------------------------------------------------------------
[qtp1615908941-218 - <<EVALUATION_CONTEXT_2>>] EVALUATIONCONTEXTIMPL::addResult-1 path: $.concat, model: [transactionId-ZFOr/MIFID], configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<EVALUATION_CONTEXT_2>>] EVALUATIONCONTEXTIMPL::addResult-2 valueResult: [[transactionId-ZFOr/MIFID]], resultIndex: 0, configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<EVALUATION_CONTEXT_2>>] EVALUATIONCONTEXTIMPL::addResult-3 valueResult: [[transactionId-ZFOr/MIFID]], resultIndex: 0, configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<COMPILED_PATH_1>>]      COMPILEDPATH::evaluate-2.2 ctx: <<EVALUATIONCTX>>, path: $.concat(...), configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<COMPILED_PATH_1>>]      COMPILEDPATH::evaluate-2.4 ctx: <<EVALUATIONCTX>>, path: $.concat(...), configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - <<COMPILED_PATH_1>>]      COMPILEDPATH::evaluate-1.1 result: <<EVALUATIONCTX>>, document: <<BODY>>, rootDocument: <<BODY>>, configuration: <<CONFIG>>
[qtp1615908941-218 - <<EVALUATION_CONTEXT_2>>] EVALUATIONCONTEXTIMPL::getValue-1.1 value: [transactionId-ZFOr/MIFID], unwrap: true
[qtp1615908941-218 - <<EVALUATION_CONTEXT_2>>] EVALUATIONCONTEXTIMPL::getValue-1.2 result: [transactionId-ZFOr/MIFID], unwrap: true
 --------------------------------------------------------------------------------------------------------------------------------------------

[qtp1615908941-218 - <<JSON_PATH_1>>]          JSONPATH::read-3 result: [transactionId-ZFOr/MIFID], jsonObject: <<BODY>>, configuration: <<CONFIG>>, jsonProvider: <<JSONPROVIDER>>
[qtp1615908941-218 - 1482307509] JSONPROVIDER::parse json: <<BODY>>
```

**Comment by Darkvater** [comment]
I did more investigation today and can quite confidently say that the problem is caused by the LRUCache used for the paths. It's not really the cache which is at fault but CompiledPath which has volatile state.

When the cache value is reused between threads it means you have the same CompiledPath but also the same FunctionPathToken which contains the parameters that holds the state of the current evaluation. You cannot share this between threads.

The issue is resolved when cache is turned off (with NOOPCache).
I can provide logs that prove this. Unfortunately I have no solution for the fix as it's very deep and complex within the library. I think the fix should be to just pass everything around and remove the state.

**Comment by dlehammer** [comment]
Seems related to https://github.com/json-path/JsonPath/issues/974 🤔

**Comment by He-Pin** [comment]
@Darkvater How about replace the Cache with one backing by guava/caffeine?

**Comment by Darkvater** [comment]
The problem is not with the caching library but the way it is used. No other cache engine can help here, the problem is a lot deeper.

**Comment by andreas-voigt-csw** [comment]
Unfortunately, I have also just encountered this problem. It still exists

**Comment by Niteshkumar152** [comment]
Hi @Darkvater 
Can you please try the same with json-path 2.4.0?

**Comment by Niteshkumar152** [comment]
Hi @Darkvater 
How did you turn the cache off?

I am using 2.9.0 version and there is no property to turn off the caching or to use NOOPCache explicitly.

Thanks in advance

**Comment by andreas-voigt-csw** [comment]
You can use as a workaround:
`CacheProvider.setCache(new NOOPCache());`

**Comment by Niteshkumar152** [comment]
Thanks @andreas-voigt-csw !!

**Comment by hyc96** [comment]
I also don't fully understand this library but to me seems like making the cache member here: https://github.com/json-path/JsonPath/blob/45333e0a310af70ad48d34d306da30af1e8e6314/json-path/src/main/java/com/jayway/jsonpath/spi/cache/CacheProvider.java#L18 could at least be a stopgap fix?

**Comment by andreas-voigt-csw** [comment]
@Darkvater is right. i still encounter the issue - even with NOOPCache().

i use different .concat($.value1, $.value2) /  .concat($.value1, $.value2, $value3) - functions on a lot of different objects of the same structure. And sometimes the concat messes values from different objects. 

I investigate it i little bit further. I used precompiled JsonPath (e.g. `JsonPath.compile(jsonPath)`) outside from the caching mechanism on different Objects (Admittedly, that's the same as using the internal cache).
Reusing Compiled JsonPath in different threads are **NOT** thead safe. Seems the issue appears when the paths contain functions e.g. concat()
